(define (large a b c)
	(define x (* c c))
	(if (> a b) (display (+ (* a a) x)))
	(if (> b a) (display (+ (* b b) x)))
)
(define (exerise1-3 a b c)
    (cond ((and (> a b) (> a c)) (large b c a))
		  ((and (> b a) (> b c)) (large a c b))
		  ((and (> c a) (> c b)) (large a b c))
	)
)
(exerise1-3 1 8 3)
